# WARNING - Generated by {fusen} from /dev/flat_utils.Rmd: do not edit by hand

test_that("detect_ui_line works", {
  expect_true(
    inherits(
      detect_ui_line(
        system.file(
          "shinyexample/R/app_ui.R",
          package = "golem"
        )
      ),
      "integer"
    )
  )
  expect_true(
    inherits(
      detect_server_line(
        system.file(
          "shinyexample/R/app_server.R",
          package = "golem"
        )
      ),
      "integer"
    )
  )
})
