# WARNING - Generated by {fusen} from /dev/flat_geyser.Rmd: do not edit by hand

test_that("geyser_hook works", {
  pth <- tempfile(pattern = "geyser")
  old_wd <- getwd()
  unlink(pth, recursive = TRUE)
  golem::create_golem(
    pth, project_hook = geyser_hook)
  expect_true(
    file.exists(
      file.path(pth, "R/app_ui.R")
    )
  )
  expect_true(
    file.exists(
      file.path(pth, "R/app_server.R")
    )
  )
  expect_true(
    grepl(
      "Old Faithful Geyser Data",
      paste(
        readLines(
          file.path(pth, "R/app_ui.R")
        ),
        collapse = ""
      )
    )
  )
  expect_true(
    grepl(
      "# Sidebar with a slider input for number of bins",
      paste(
        readLines(
          file.path(pth, "R/app_ui.R")
        ),
        collapse = ""
      )
    )
  )
  expect_true(
    grepl(
      "output\\$distPlot <- renderPlot",
      paste(
        readLines(file.path(pth, "R/app_server.R")),
        collapse = ""
      )
    )
  )
  expect_true(
    grepl(
      "histogram with the specified number of bins",
      paste(
        readLines(
          file.path(pth, "R/app_server.R")), collapse = "")
    )
  )
  setwd(old_wd)
})
